apiVersion: v1
kind: Service
metadata:
  name: my-nginx-lb
  labels:
    app: my-nginx
spec:
  clusterIP: 10.102.17.197
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1